Address is now defined as a simple string
multiversx/mx-sdk-specs pull request #27
Opened 2023-10-12 11:33 UTC by andreibancioiu

2023-10-12 11:40 UTC, iulianpascalau requested changes

2023-10-12 12:52 UTC, andrei-marinica commented on sdk-core/address.md
> +Generally speaking, the `Address` type should be a `string` in all implementations.
In mandos we use the value interpreter to express things in textual form:
`bech32:erd123445......`
`address:dummy_address`
`0x1234aaa...`

In Rust I want to create string wrappers that have the same function: making an address very readable, while also specifying the exact format
`Bech32("erd123445......")`
`TestAddress"dummy_address")`
`Hex("0x1234aaa...")`

I think making the exact format used obvious is essential.

2023-10-12 12:56 UTC, andrei-marinica commented on sdk-core/address.md
> +Generally speaking, the `Address` type should be a `string` in all implementations.
Can't we also write in these languages something in the spirit of newtype? An object that wraps the string, while also giving some additional context?

2023-10-12 20:01 UTC, andreibancioiu commented
Change is abandoned. Components will only be slightly adjusted, but in a different PR.

2023-10-12 20:01 UTC, closed without merging

2023-10-16 07:42 UTC, iulianpascalau commented on sdk-core/address.md
> +Generally speaking, the `Address` type should be a `string` in all implementations.
@andrei-marinica that is why we had the IAddress definition. A struct that made the conversions automatically so the confusion between the string types was eliminated.